Update README.md
UCLALibrary/waveform-service pull request #1
Opened 2024-05-29 16:45 UTC by angelahuqing

2024-05-29 17:03 UTC, DRickard approved these changes

2024-05-29 18:58 UTC, ksclarke requested changes
Maybe say "A/V pipeline project" for now instead of "Pairtree proect" since we'll be calling the new pipeline something different.

2024-05-30 17:36 UTC, DRickard approved these changes

2024-05-31 16:21 UTC, ksclarke approved these changes

2024-05-31 16:54 UTC, merged